-- Creating tables for PH-EmployeeDB
CREATE TABLE abnb_listings (
     id VARCHAR NOT NULL,
     host_response_rate VARCHAR,
     host_is_superhost VARCHAR,
     host_identity_verified VARCHAR,
     neighbourhood_cleansed VARCHAR,
     neighbourhood_group_cleansed VARCHAR,
     state VARCHAR,
     country_code VARCHAR,
     room_type VARCHAR,
     accomodates VARCHAR,
     bathrooms FLOAT4,
     bedrooms FLOAT4,
     beds FLOAT4,
     bed_type VARCHAR,
     amenities VARCHAR,
     price FLOAT4,
     security_deposit FLOAT4,
     cleaning_fee VARCHAR,
     guests_included FLOAT4,
     extra_people FLOAT4,
     minimum_nights FLOAT4,
     maximum_nights FLOAT4,
     availability_365 INT,
     number_of_reviews INT,
     review_scores_rating VARCHAR,
     review_scores_accuracy VARCHAR,
     review_scores_cleanliness VARCHAR,
     review_scores_checkin VARCHAR,
     review_scores_communication VARCHAR,
     review_scores_location VARCHAR,
     review_scores_value VARCHAR,
     instant_bookable VARCHAR,
     is_business_travel_ready VARCHAR,
     cancellation_policy VARCHAR,
     require_guest_profile_picture VARCHAR,
     require_guest_phone_verification VARCHAR,
     reviews_per_month FLOAT4,
     is_success INT
);

